datacenter: "RS00"
cluster: "vcs-rs-00"
host: "fvmw-esxi-01.example.com"
datastore: "workload_share"
network: "segment-migrating-to-ocpvirt"
folder: "Roadshow"
vms:
  - name: "database"
    guestId: "centos8_64Guest"
    disk: "database.vmdk"
    memoryMB: 2048
    numCPUs: 1
    firmware: "efi"
  - name: "winweb01"
    guestId: "windows2019srvNext_64Guest"
    disk: "winweb01.vmdk"
    memoryMB: 6144
    numCPUs: 2
    firmware: "efi"
  - name: "winweb02"
    guestId: "windows2019srvNext_64Guest"
    disk: "winweb02.vmdk"
    memoryMB: 6144
    numCPUs: 2
    firmware: "efi"
  - name: "haproxy"
    guestId: "other26xLinux64Guest"
    disk: "haproxy.vmdk"
    memoryMB: 4096
    numCPUs: 2
    firmware: "efi"
